### ISSUE TITLE
Example for attaching pdf

### ISSUE THREAD

**Issue by janviparikh** [samoconnor/AWSSES.jl#1]
Hi,
Could you please provide an example to attach a pdf. I get a Diagnostic-Code: smtp; 501 Syntax error - line too long  when using [("d.pdf","application/pdf",data)] for attachment. data here is a bytearray

**Comment by samoconnor** [comment]
Hi @janvidpa,

I've just pushed this commit to AWSCore.jl https://github.com/samoconnor/AWSCore.jl/commit/9330a7b5131dde536ff6645f25822dd552c2c398 With this change, the following example works for me...

``` julia
f = open("/Users/sam/stuff/foo.pdf")
d = readbytes(f)
ses_send_attachments(aws; to="xxx@xxx", from="xxx@xxx", subject="test", body="foo",
                          attachments=[("d.pdf", "application/pdf", d)])
```

Please try doing `Pkg.checkout("AWSCore", pull=true)`, to get the latest unreleased `AWSCore`.
If this works for you I'll make a new release with the fix.
(You can then to `Pkg.free("AWSCore")` to switch back to the release version.)

**Comment by janviparikh** [comment]
Hi @samoconnor,
This works for me. Thanks!

**Comment by samoconnor** [comment]
No problem @janvidpa, thanks for reporting the problem.
As soon as #4752 is merged, you should be able to go back to the release version of AWSCore.jl

**Comment by janviparikh** [comment]
@samoconnor when trying to send attachments an extra untitled txt document is also received on windows, this doesn't seem to happen on linux.

**Comment by samoconnor** [comment]
Can you please:
- add a statement like `open(io->write(io, raw), "raw_mime.txt", "w")` on this line:
  https://github.com/samoconnor/AWSSES.jl/blob/master/src/AWSSES.jl#L48
- send me the resulting `raw_mime.txt`
- also, send a copy of the email to `sam@octe.ch`

My guess is that there is some subtlety of the [MIME multipart](https://github.com/samoconnor/AWSCore.jl/blob/master/src/mime.jl#L40) generation that has to be just-so for Outlook to be happy. Googling for "outlook untitled attachment finds lots of hits".

**Comment by janviparikh** [comment]
Have sent you a test mail.
[raw_mime.txt](https://github.com/samoconnor/AWSSES.jl/files/171525/raw_mime.txt)

**Comment by samoconnor** [comment]
Got it.
In outlook, what is the exact name of the untitled attachment and what is the content?

**Comment by janviparikh** [comment]
Untitled attachment 00008.txt (the numeric part of the name is random 11,13,8 etc)
Its an empty file

**Comment by samoconnor** [comment]
Can you try...
- set `mime *= "Content-Transfer-Encoding: 7bit\n"` on this line : https://github.com/samoconnor/AWSCore.jl/blob/master/src/mime.jl#L60
- Change `"text/plain"` to `"text/plain";\n    charset=us-ascii"` on this line: https://github.com/samoconnor/AWSSES.jl/blob/master/src/AWSSES.jl#L73 (4 spaces between `\n` and `charset=`)
- Putting a newline at the end of `body="Test Body"` when you call `ses_send_attachments` (e.g. `body="Test Body\n"`)

**Comment by janviparikh** [comment]
No luck with these changes
[raw_mime.txt](https://github.com/samoconnor/AWSSES.jl/files/171552/raw_mime.txt)

**Comment by samoconnor** [comment]
Not sure if the extra space between `text/plain` and  `;` matters, but it might... (i.e. the `raw_mime.txt` you attached has an extra space).

**Comment by janviparikh** [comment]
Removing the space dint make a difference.

**Comment by samoconnor** [comment]
What about changing this line : https://github.com/samoconnor/AWSCore.jl/blob/master/src/mime.jl#L71 
from `--$boundary` to `--$boundary--` . ?

**Comment by samoconnor** [comment]
wait... sorry, thats wrong... standby...

**Comment by samoconnor** [comment]
Here is a revised `mime_multipart` function that tries to get the "--" at the end of the last boundary right (https://github.com/samoconnor/AWSCore.jl/blob/master/src/mime.jl)

``` julia
function mime_multipart(header::AbstractString, parts::Array)

    boundary = "=PRZLn8Nm1I82df0Dtj4ZvJi="

    mime = 
    """
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="$boundary"
    $header

    """

    for (filename, content_type, content) in parts

        mime *= "--$boundary\n"

        if filename != ""
            mime *= "Content-Type: $content_type;\n    name=$filename\n"
            mime *= "Content-Disposition: attachment;\n    filename=$filename\n"
        else
            mime *= "Content-Type: $content_type\n"
        end

        if isa(content, AbstractString)
            mime *= "Content-Transfer-Encoding: binary\n"
        else
            mime *= "Content-Transfer-Encoding: base64\n"
            b64 = base64encode(content)
            b64 = [b64[i:min(length(b64),i+75)] for i in 1:76:length(b64)]
            content = join(b64, "\n")
        end

        mime *= "\n$content\n"
    end

    mime *= "--$boundary--\n"
    return mime
end
```

**Comment by janviparikh** [comment]
Works. Thanks...
I also wanted to know if there is any provision for sending the name of owner of the from address.

**Comment by samoconnor** [comment]
I think you can just do `from="Sam O'Connor <sam@octe.ch>"`.

**Comment by janviparikh** [comment]
Thanks. Its actually the other way around we need to do from=" <sam@octe.ch> Sam O'Connor "
